# Generated by Django 3.1.7 on 2021-05-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreetProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='current',
            name='current',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
