# Generated by Django 3.1.7 on 2021-06-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreetProject', '0002_current_current'),
    ]

    operations = [
        migrations.RenameField(
            model_name='current',
            old_name='current',
            new_name='button',
        ),
        migrations.AddField(
            model_name='current',
            name='light',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
